export const IndianStateNames = {
  AN: { name: "Andaman and Nicobar Islands" },
  AP: { name: "Andhra Pradesh" },
  AR: { name: "Arunachal Pradesh" },
  AS: { name: "Assam" },
  BR: { name: "Bihar" },
  CH: { name: "Chandigarh" },
  CT: { name: "Chhattisgarh" },
  DL: { name: "Delhi" },
  DN: { name: "Dadra and Nagar Haveli and Daman and Diu" },
  GA: { name: "Goa" },
  GJ: { name: "Gujarat" },
  HP: { name: "Himachal Pradesh" },
  HR: { name: "Haryana" },
  JH: { name: "Jharkhand" },
  JK: { name: "Jammu and Kashmir" },
  KA: { name: "Karnataka" },
  KL: { name: "Kerala" },
  LA: { name: "Ladakh" },
  LD: { name: "Lakshadweep" },
  MH: { name: "Maharashtra" },
  ML: { name: "Meghalaya" },
  MN: { name: "Manipur" },
  MP: { name: "Madhya Pradesh" },
  MZ: { name: "Mizoram" },
  NL: { name: "Nagaland" },
  OR: { name: "Odisha" },
  PB: { name: "Punjab" },
  PY: { name: "Puducherry" },
  RJ: { name: "Rajasthan" },
  SK: { name: "Sikkim" },
  TG: { name: "Telangana" },
  TN: { name: "Tamil Nadu" },
  TR: { name: "Tripura" },
  TT: { name: "India" },
  UP: { name: "Uttar Pradesh" },
  UT: { name: "Uttarakhand" },
  WB: { name: "West Bengal" }
};
